# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Competition.create(name:"Ligue 1 Uber Eats",country:"France")

# Club.create(name:"Paris Saint-Germain",acronym:"PSG",shortname:"Paris SG")
# Club.create(name:"Lille OSC",acronym:"LOSC",shortname:"Lille")
# Club.create(name:"Stade Rennais",acronym:"SR",shortname:"Rennes")
# Club.create(name:"Olympique de Marseille",acronym:"OM",shortname:"Marseille")
# Club.create(name:"Olymique Lyonnais",acronym:"OL",shortname:"Lyon")
# Club.create(name:"AS Monaco",acronym:"ASM",shortname:"Monaco")
# Club.create(name:"Montpellier HSC",acronym:"MHSC",shortname:"Montpellier")
# Club.create(name:"OGC Nice",acronym:"OGCN",shortname:"Nice")
# Club.create(name:"SCO Angers",acronym:"SCO",shortname:"Angers")
# Club.create(name:"FC Metz",acronym:"FCM",shortname:"Metz")
# Club.create(name:"RC Lens",acronym:"RCL",shortname:"Lens")
# Club.create(name:"FC Girondins de Bordeaux",acronym:"FCGB",shortname:"Bordeaux")
# Club.create(name:"Stade Brestois",acronym:"SB29",shortname:"Brest")
# Club.create(name:"FC Nantes",acronym:"FCN",shortname:"Nantes")
# Club.create(name:"AS Saint-Étienne",acronym:"ASSE",shortname:"St-Étienne")
# Club.create(name:"Stade de Reims",acronym:"SdR",shortname:"Reims")
# Club.create(name:"FC Lorient",acronym:"FCL",shortname:"Lorient")
# Club.create(name:"Nîmes Olympique",acronym:"NO",shortname:"Nîmes")
# Club.create(name:"RC Strasbourg",acronym:"RCS",shortname:"Strasbourg")
# Club.create(name:"Dijon FCO",acronym:"DFCO",shortname:"Dijon")

# Team.create(level:"Pro men's squad",club:Club.find(1))
# Team.create(level:"Pro men's squad",club:Club.find(2))
# Team.create(level:"Pro men's squad",club:Club.find(3))
# Team.create(level:"Pro men's squad",club:Club.find(4))
# Team.create(level:"Pro men's squad",club:Club.find(5))
# Team.create(level:"Pro men's squad",club:Club.find(6))
# Team.create(level:"Pro men's squad",club:Club.find(7))
# Team.create(level:"Pro men's squad",club:Club.find(8))
# Team.create(level:"Pro men's squad",club:Club.find(9))
# Team.create(level:"Pro men's squad",club:Club.find(10))
# Team.create(level:"Pro men's squad",club:Club.find(11))
# Team.create(level:"Pro men's squad",club:Club.find(12))
# Team.create(level:"Pro men's squad",club:Club.find(13))
# Team.create(level:"Pro men's squad",club:Club.find(14))
# Team.create(level:"Pro men's squad",club:Club.find(15))
# Team.create(level:"Pro men's squad",club:Club.find(16))
# Team.create(level:"Pro men's squad",club:Club.find(17))
# Team.create(level:"Pro men's squad",club:Club.find(18))
# Team.create(level:"Pro men's squad",club:Club.find(19))
# Team.create(level:"Pro men's squad",club:Club.find(20))

# Season.create(competition:Competition.find(1),startyear:"2020-2021")